# Form implementation generated from reading ui file '10_Proto_10.ui'

from PyQt5 import QtCore, QtGui, QtWidgets

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(975, 618)
        MainWindow.setMinimumSize(QtCore.QSize(975, 618))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.NoRole, brush)
        MainWindow.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.F_Boutons = QtWidgets.QFrame(self.centralwidget)
        self.F_Boutons.setMinimumSize(QtCore.QSize(110, 517))
        self.F_Boutons.setMaximumSize(QtCore.QSize(110, 16777215))
        self.F_Boutons.setFrameShape(QtWidgets.QFrame.Panel)
        self.F_Boutons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.F_Boutons.setObjectName("F_Boutons")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.F_Boutons)
        self.verticalLayout.setObjectName("verticalLayout")
        self.B_Import_CSV = QtWidgets.QPushButton(self.F_Boutons)
        self.B_Import_CSV.setMinimumSize(QtCore.QSize(90, 90))
        self.B_Import_CSV.setMaximumSize(QtCore.QSize(90, 90))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.B_Import_CSV.setFont(font)
        self.B_Import_CSV.setAutoFillBackground(False)
        self.B_Import_CSV.setStyleSheet("background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0.5 rgba(70, 70, 70, 255), stop:1 rgba(200, 200, 200, 255));\n"
"color: rgb(240, 240, 240);")
        self.B_Import_CSV.setObjectName("B_Import_CSV")
        self.verticalLayout.addWidget(self.B_Import_CSV)
        self.B_Traiter_lignes = QtWidgets.QPushButton(self.F_Boutons)
        self.B_Traiter_lignes.setMinimumSize(QtCore.QSize(90, 90))
        self.B_Traiter_lignes.setMaximumSize(QtCore.QSize(90, 90))
        self.B_Traiter_lignes.setStyleSheet(r"background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0.5 rgba(70, 70, 70, 255), stop:1 rgba(200, 200, 200, 255));\n"
"color: rgb(240, 240, 240);")
        self.B_Traiter_lignes.setObjectName("B_Traiter_lignes")
        self.verticalLayout.addWidget(self.B_Traiter_lignes)
        self.B_Impression = QtWidgets.QPushButton(self.F_Boutons)
        self.B_Impression.setMinimumSize(QtCore.QSize(90, 90))
        self.B_Impression.setMaximumSize(QtCore.QSize(90, 90))
        self.B_Impression.setStyleSheet("background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0.5 rgba(70, 70, 70, 255), stop:1 rgba(200, 200, 200, 255));\n"
"color: rgb(240, 240, 240);")
        self.B_Impression.setObjectName("B_Impression")
        self.verticalLayout.addWidget(self.B_Impression)
        self.B_Internet = QtWidgets.QPushButton(self.F_Boutons)
        self.B_Internet.setMinimumSize(QtCore.QSize(90, 90))
        self.B_Internet.setMaximumSize(QtCore.QSize(90, 90))
        self.B_Internet.setStyleSheet("background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0.5 rgba(70, 70, 70, 255), stop:1 rgba(200, 200, 200, 255));\n"
"color: rgb(240, 240, 240);")
        self.B_Internet.setObjectName("B_Internet")
        self.verticalLayout.addWidget(self.B_Internet)
        spacerItem = QtWidgets.QSpacerItem(20, 110, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.B_Quitter = QtWidgets.QPushButton(self.F_Boutons)
        self.B_Quitter.setMinimumSize(QtCore.QSize(90, 90))
        self.B_Quitter.setMaximumSize(QtCore.QSize(90, 90))
        self.B_Quitter.setStyleSheet("background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0.5 rgba(70, 70, 70, 255), stop:1 rgba(200, 200, 200, 255));\n"
"color: rgb(240, 240, 240);")
        self.B_Quitter.setObjectName("B_Quitter")
        self.verticalLayout.addWidget(self.B_Quitter)
        self.gridLayout_4.addWidget(self.F_Boutons, 0, 0, 2, 1)
        self.F_Infos_generales = QtWidgets.QFrame(self.centralwidget)
        self.F_Infos_generales.setMinimumSize(QtCore.QSize(840, 120))
        self.F_Infos_generales.setMaximumSize(QtCore.QSize(16777215, 120))
        self.F_Infos_generales.setStyleSheet("color: rgb(240, 240, 240);")
        self.F_Infos_generales.setFrameShape(QtWidgets.QFrame.Panel)
        self.F_Infos_generales.setFrameShadow(QtWidgets.QFrame.Raised)
        self.F_Infos_generales.setLineWidth(1)
        self.F_Infos_generales.setObjectName("F_Infos_generales")
        self.gridLayout = QtWidgets.QGridLayout(self.F_Infos_generales)
        self.gridLayout.setObjectName("gridLayout")
        self.label_18 = QtWidgets.QLabel(self.F_Infos_generales)
        self.label_18.setMinimumSize(QtCore.QSize(34, 16))
        self.label_18.setMaximumSize(QtCore.QSize(34, 16))
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 3, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.F_Infos_generales)
        self.label.setMinimumSize(QtCore.QSize(110, 20))
        self.label.setMaximumSize(QtCore.QSize(110, 20))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.L_Nom_du_fichier_de_balance_charge = QtWidgets.QLabel(self.F_Infos_generales)
        self.L_Nom_du_fichier_de_balance_charge.setObjectName("L_Nom_du_fichier_de_balance_charge")
        self.gridLayout.addWidget(self.L_Nom_du_fichier_de_balance_charge, 3, 9, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.F_Infos_generales)
        self.label_3.setMinimumSize(QtCore.QSize(170, 20))
        self.label_3.setMaximumSize(QtCore.QSize(170, 20))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 8, 1, 1)
        self.L_Date_update = QtWidgets.QLabel(self.F_Infos_generales)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.L_Date_update.setPalette(palette)
        self.L_Date_update.setObjectName("L_Date_update")
        self.gridLayout.addWidget(self.L_Date_update, 0, 9, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(422, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 7, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.F_Infos_generales)
        self.label_4.setMinimumSize(QtCore.QSize(110, 20))
        self.label_4.setMaximumSize(QtCore.QSize(110, 20))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.F_Infos_generales)
        self.label_2.setMinimumSize(QtCore.QSize(110, 20))
        self.label_2.setMaximumSize(QtCore.QSize(110, 20))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 7, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 7, 1, 1)
        self.L_Nom_du_fichier_de_comptes_charge = QtWidgets.QLabel(self.F_Infos_generales)
        self.L_Nom_du_fichier_de_comptes_charge.setObjectName("L_Nom_du_fichier_de_comptes_charge")
        self.gridLayout.addWidget(self.L_Nom_du_fichier_de_comptes_charge, 2, 9, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.F_Infos_generales)
        self.label_7.setMinimumSize(QtCore.QSize(170, 20))
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 8, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.F_Infos_generales)
        self.label_5.setMinimumSize(QtCore.QSize(170, 20))
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 8, 1, 1)
        self.L_total_comptes_lui = QtWidgets.QLabel(self.F_Infos_generales)
        self.L_total_comptes_lui.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.L_total_comptes_lui.setObjectName("L_total_comptes_lui")
        self.gridLayout.addWidget(self.L_total_comptes_lui, 2, 4, 1, 1)
        self.L_total_balance_lui = QtWidgets.QLabel(self.F_Infos_generales)
        self.L_total_balance_lui.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.L_total_balance_lui.setObjectName("L_total_balance_lui")
        self.gridLayout.addWidget(self.L_total_balance_lui, 2, 5, 1, 1)
        self.L_total_balance_elle = QtWidgets.QLabel(self.F_Infos_generales)
        self.L_total_balance_elle.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.L_total_balance_elle.setObjectName("L_total_balance_elle")
        self.gridLayout.addWidget(self.L_total_balance_elle, 3, 5, 1, 1)
        self.L_total_comptes_elle = QtWidgets.QLabel(self.F_Infos_generales)
        self.L_total_comptes_elle.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.L_total_comptes_elle.setObjectName("L_total_comptes_elle")
        self.gridLayout.addWidget(self.L_total_comptes_elle, 3, 4, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.F_Infos_generales)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 1, 4, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.F_Infos_generales)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 1, 5, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.F_Infos_generales)
        self.label_16.setMinimumSize(QtCore.QSize(34, 16))
        self.label_16.setMaximumSize(QtCore.QSize(34, 16))
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 1, 3, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.F_Infos_generales)
        self.label_17.setMinimumSize(QtCore.QSize(34, 16))
        self.label_17.setMaximumSize(QtCore.QSize(34, 16))
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 2, 3, 1, 1)
        self.L_Total_lui = QtWidgets.QLabel(self.F_Infos_generales)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.L_Total_lui.setFont(font)
        self.L_Total_lui.setObjectName("L_Total_lui")
        self.gridLayout.addWidget(self.L_Total_lui, 2, 2, 1, 1)
        self.L_Total_elle = QtWidgets.QLabel(self.F_Infos_generales)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.L_Total_elle.setFont(font)
        self.L_Total_elle.setObjectName("L_Total_elle")
        self.gridLayout.addWidget(self.L_Total_elle, 3, 2, 1, 1)
        self.L_Total = QtWidgets.QLabel(self.F_Infos_generales)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.L_Total.setFont(font)
        self.L_Total.setObjectName("L_Total")
        self.gridLayout.addWidget(self.L_Total, 0, 2, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.F_Infos_generales)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 1, 6, 1, 1)
        self.L_total_annee_precedente_lui = QtWidgets.QLabel(self.F_Infos_generales)
        self.L_total_annee_precedente_lui.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.L_total_annee_precedente_lui.setObjectName("L_total_annee_precedente_lui")
        self.gridLayout.addWidget(self.L_total_annee_precedente_lui, 2, 6, 1, 1)
        self.L_total_annee_precedente_elle = QtWidgets.QLabel(self.F_Infos_generales)
        self.L_total_annee_precedente_elle.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.L_total_annee_precedente_elle.setObjectName("L_total_annee_precedente_elle")
        self.gridLayout.addWidget(self.L_total_annee_precedente_elle, 3, 6, 1, 1)
        self.gridLayout_4.addWidget(self.F_Infos_generales, 0, 1, 1, 1)
        self.TW_Donnees = QtWidgets.QTabWidget(self.centralwidget)
        self.TW_Donnees.setMinimumSize(QtCore.QSize(817, 420))
        self.TW_Donnees.setStyleSheet("background-color: rgb(90, 90, 90);")
        self.TW_Donnees.setObjectName("TW_Donnees")
        self.T_Comptes = QtWidgets.QWidget()
        self.T_Comptes.setMinimumSize(QtCore.QSize(831, 395))
        self.T_Comptes.setStyleSheet("")
        self.T_Comptes.setObjectName("T_Comptes")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.T_Comptes)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.TV_Comptes = QtWidgets.QTableView(self.T_Comptes)
        self.TV_Comptes.setMinimumSize(QtCore.QSize(817, 382))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.TV_Comptes.setPalette(palette)
        self.TV_Comptes.setObjectName("TV_Comptes")
        self.gridLayout_3.addWidget(self.TV_Comptes, 0, 0, 1, 1)
        self.TW_Donnees.addTab(self.T_Comptes, "")
        self.T_Balance = QtWidgets.QWidget()
        self.T_Balance.setMinimumSize(QtCore.QSize(831, 395))
        self.T_Balance.setObjectName("T_Balance")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.T_Balance)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.F_Balance = QtWidgets.QFrame(self.T_Balance)
        self.F_Balance.setMinimumSize(QtCore.QSize(817, 170))
        self.F_Balance.setMaximumSize(QtCore.QSize(16777215, 170))
        self.F_Balance.setFrameShape(QtWidgets.QFrame.Panel)
        self.F_Balance.setFrameShadow(QtWidgets.QFrame.Raised)
        self.F_Balance.setObjectName("F_Balance")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.F_Balance)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.CB_payeur = QtWidgets.QComboBox(self.F_Balance)
        self.CB_payeur.setMinimumSize(QtCore.QSize(150, 30))
        self.CB_payeur.setMaximumSize(QtCore.QSize(150, 30))
        self.CB_payeur.setStyleSheet("background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0.5 rgba(70, 70, 70, 255), stop:1 rgba(200, 200, 200, 255));\n"
"color: rgb(240, 240, 240);")
        self.CB_payeur.setObjectName("CB_payeur")
        self.CB_payeur.addItem("")
        self.CB_payeur.addItem("")
        self.gridLayout_2.addWidget(self.CB_payeur, 2, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.F_Balance)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.F_Balance)
        self.label_12.setMinimumSize(QtCore.QSize(34, 16))
        self.label_12.setMaximumSize(QtCore.QSize(34, 16))
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 2, 1, 1, 1)
        self.CW_Choix_de_la_date = QtWidgets.QCalendarWidget(self.F_Balance)
        self.CW_Choix_de_la_date.setMinimumSize(QtCore.QSize(256, 141))
        self.CW_Choix_de_la_date.setMaximumSize(QtCore.QSize(256, 141))
        self.CW_Choix_de_la_date.setObjectName("CW_Choix_de_la_date")
        self.gridLayout_2.addWidget(self.CW_Choix_de_la_date, 0, 0, 3, 1)
        self.B_Ajouter_dans_balance = QtWidgets.QPushButton(self.F_Balance)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.B_Ajouter_dans_balance.sizePolicy().hasHeightForWidth())
        self.B_Ajouter_dans_balance.setSizePolicy(sizePolicy)
        self.B_Ajouter_dans_balance.setMinimumSize(QtCore.QSize(100, 150))
        self.B_Ajouter_dans_balance.setMaximumSize(QtCore.QSize(100, 150))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(1.0, 1.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.RepeatSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.5, QtGui.QColor(70, 70, 70))
        gradient.setColorAt(1.0, QtGui.QColor(200, 200, 200))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(1.0, 1.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.RepeatSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.5, QtGui.QColor(70, 70, 70))
        gradient.setColorAt(1.0, QtGui.QColor(200, 200, 200))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(1.0, 1.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.RepeatSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.5, QtGui.QColor(70, 70, 70))
        gradient.setColorAt(1.0, QtGui.QColor(200, 200, 200))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(1.0, 1.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.RepeatSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.5, QtGui.QColor(70, 70, 70))
        gradient.setColorAt(1.0, QtGui.QColor(200, 200, 200))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(1.0, 1.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.RepeatSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.5, QtGui.QColor(70, 70, 70))
        gradient.setColorAt(1.0, QtGui.QColor(200, 200, 200))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(1.0, 1.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.RepeatSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.5, QtGui.QColor(70, 70, 70))
        gradient.setColorAt(1.0, QtGui.QColor(200, 200, 200))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(1.0, 1.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.RepeatSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.5, QtGui.QColor(70, 70, 70))
        gradient.setColorAt(1.0, QtGui.QColor(200, 200, 200))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(1.0, 1.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.RepeatSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.5, QtGui.QColor(70, 70, 70))
        gradient.setColorAt(1.0, QtGui.QColor(200, 200, 200))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(1.0, 1.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.RepeatSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.5, QtGui.QColor(70, 70, 70))
        gradient.setColorAt(1.0, QtGui.QColor(200, 200, 200))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.B_Ajouter_dans_balance.setPalette(palette)
        self.B_Ajouter_dans_balance.setStyleSheet("background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0.5 rgba(70, 70, 70, 255), stop:1 rgba(200, 200, 200, 255));\n"
"color: rgb(240, 240, 240);")
        self.B_Ajouter_dans_balance.setObjectName("B_Ajouter_dans_balance")
        self.gridLayout_2.addWidget(self.B_Ajouter_dans_balance, 0, 6, 3, 1)
        self.label_6 = QtWidgets.QLabel(self.F_Balance)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 2, 1, 1)
        self.LE_Libelle = QtWidgets.QLineEdit(self.F_Balance)
        self.LE_Libelle.setMinimumSize(QtCore.QSize(150, 30))
        self.LE_Libelle.setMaximumSize(QtCore.QSize(150, 30))
        self.LE_Libelle.setStyleSheet("background-color: rgb(90, 90, 90);\n"
"color: rgb(240, 240, 240);\n"
"border: 1px solid rgb(240, 240, 240);")
        self.LE_Libelle.setObjectName("LE_Libelle")
        self.gridLayout_2.addWidget(self.LE_Libelle, 0, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.F_Balance)
        self.label_10.setMinimumSize(QtCore.QSize(34, 16))
        self.label_10.setMaximumSize(QtCore.QSize(34, 16))
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 1, 1, 1)
        self.LE_Montant = QtWidgets.QLineEdit(self.F_Balance)
        self.LE_Montant.setMinimumSize(QtCore.QSize(150, 30))
        self.LE_Montant.setMaximumSize(QtCore.QSize(150, 30))
        self.LE_Montant.setStyleSheet("background-color: rgb(90, 90, 90);\n"
"color: rgb(240, 240, 240);\n"
"border: 1px solid rgb(240, 240, 240);\n"
"")
        self.LE_Montant.setObjectName("LE_Montant")
        self.gridLayout_2.addWidget(self.LE_Montant, 1, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.F_Balance)
        self.label_11.setMinimumSize(QtCore.QSize(34, 16))
        self.label_11.setMaximumSize(QtCore.QSize(34, 16))
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.F_Balance)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.F_Balance)
        self.label_13.setMinimumSize(QtCore.QSize(34, 16))
        self.label_13.setMaximumSize(QtCore.QSize(34, 16))
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 0, 5, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.F_Balance)
        self.label_14.setMinimumSize(QtCore.QSize(34, 16))
        self.label_14.setMaximumSize(QtCore.QSize(34, 16))
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 1, 5, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.F_Balance)
        self.label_15.setMinimumSize(QtCore.QSize(34, 16))
        self.label_15.setMaximumSize(QtCore.QSize(34, 16))
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 2, 5, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 0, 4, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 1, 4, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 2, 4, 1, 1)
        self.verticalLayout_2.addWidget(self.F_Balance)
        self.TV_Balance = QtWidgets.QTableView(self.T_Balance)
        self.TV_Balance.setMinimumSize(QtCore.QSize(817, 206))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.TV_Balance.setPalette(palette)
        self.TV_Balance.setObjectName("TV_Balance")
        self.verticalLayout_2.addWidget(self.TV_Balance)
        self.TW_Donnees.addTab(self.T_Balance, "")
        self.gridLayout_4.addWidget(self.TW_Donnees, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.TW_Donnees.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Comptes", None))
        self.B_Import_CSV.setText(_translate("MainWindow", "1 - Importer\n"
"un fichier CSV", None))
        self.B_Traiter_lignes.setText(_translate("MainWindow", "2 - Traiter \n"
"des lignes", None))
        self.B_Impression.setText(_translate("MainWindow", "3 - Imprimer\n"
"les comptes \n"
"sur une période", None))
        self.B_Internet.setText(_translate("MainWindow", "4 - Aller sur\n"
"le site de \n"
"la banque", None))
        self.B_Quitter.setText(_translate("MainWindow", "Quitter", None))
        self.label.setText(_translate("MainWindow", "TOTAL sur le compte", None))
        self.L_Nom_du_fichier_de_balance_charge.setText(_translate("MainWindow", "TextLabel", None))
        self.label_3.setText(_translate("MainWindow", "Date de la dernière mise-à-jour", None))
        self.L_Date_update.setText(_translate("MainWindow", "TextLabel", None))
        self.label_4.setText(_translate("MainWindow", "Total elle", None))
        self.label_2.setText(_translate("MainWindow", "Total lui", None))
        self.L_Nom_du_fichier_de_comptes_charge.setText(_translate("MainWindow", "TextLabel", None))
        self.label_7.setText(_translate("MainWindow", "Fichier de balance chargé", None))
        self.label_5.setText(_translate("MainWindow", "Fichier de comptes chargé", None))
        self.L_total_comptes_lui.setText(_translate("MainWindow", "0.0", None))
        self.L_total_balance_lui.setText(_translate("MainWindow", "0.0", None))
        self.L_total_balance_elle.setText(_translate("MainWindow", "0.0", None))
        self.L_total_comptes_elle.setText(_translate("MainWindow", "0.0", None))
        self.label_24.setText(_translate("MainWindow", "Totaux comptes", None))
        self.label_25.setText(_translate("MainWindow", "Totaux balance", None))
        self.L_Total_lui.setText(_translate("MainWindow", "0.0", None))
        self.L_Total_elle.setText(_translate("MainWindow", "0.0", None))
        self.L_Total.setText(_translate("MainWindow", "0.0", None))
        self.label_26.setText(_translate("MainWindow", "<html><head/><body><p>Totaux année précédente</p></body></html>", None))
        self.L_total_annee_precedente_lui.setText(_translate("MainWindow", "0.0", None))
        self.L_total_annee_precedente_elle.setText(_translate("MainWindow", "0.0", None))
        self.TW_Donnees.setTabText(self.TW_Donnees.indexOf(self.T_Comptes), _translate("MainWindow", "Comptes", None))
        self.CB_payeur.setItemText(0, _translate("MainWindow", "lui", None))
        self.CB_payeur.setItemText(1, _translate("MainWindow", "elle", None))
        self.label_9.setText(_translate("MainWindow", "Payé par", None))
        self.B_Ajouter_dans_balance.setText(_translate("MainWindow", "Ajouter", None))
        self.label_6.setText(_translate("MainWindow", "Libellé", None))
        self.label_8.setText(_translate("MainWindow", "Montant (€)", None))
        self.TW_Donnees.setTabText(self.TW_Donnees.indexOf(self.T_Balance), _translate("MainWindow", "Balance", None))

