# Form implementation generated from reading ui file '02_Calculatrice_trajets_2.ui'

from PyQt5 import QtCore, QtGui, QtWidgets

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(450, 295)
        Dialog.setMinimumSize(QtCore.QSize(450, 295))
        Dialog.setMaximumSize(QtCore.QSize(450, 295))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Dialog.setPalette(palette)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setMinimumSize(QtCore.QSize(300, 30))
        self.label.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.LE_Distance = QtWidgets.QLineEdit(Dialog)
        self.LE_Distance.setMinimumSize(QtCore.QSize(120, 30))
        self.LE_Distance.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LE_Distance.setFont(font)
        self.LE_Distance.setStyleSheet("background-color: rgb(90, 90, 90);\n"
"color: rgb(240, 240, 240);\n"
"border: 1px solid rgb(240, 240, 240);")
        self.LE_Distance.setObjectName("LE_Distance")
        self.gridLayout.addWidget(self.LE_Distance, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setMinimumSize(QtCore.QSize(300, 30))
        self.label_2.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.LE_Prix_carburant = QtWidgets.QLineEdit(Dialog)
        self.LE_Prix_carburant.setMinimumSize(QtCore.QSize(120, 30))
        self.LE_Prix_carburant.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LE_Prix_carburant.setFont(font)
        self.LE_Prix_carburant.setStyleSheet("background-color: rgb(90, 90, 90);\n"
"color: rgb(240, 240, 240);\n"
"border: 1px solid rgb(240, 240, 240);")
        self.LE_Prix_carburant.setObjectName("LE_Prix_carburant")
        self.gridLayout.addWidget(self.LE_Prix_carburant, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setMinimumSize(QtCore.QSize(300, 30))
        self.label_3.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.LE_Consommation = QtWidgets.QLineEdit(Dialog)
        self.LE_Consommation.setMinimumSize(QtCore.QSize(120, 30))
        self.LE_Consommation.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LE_Consommation.setFont(font)
        self.LE_Consommation.setStyleSheet("background-color: rgb(90, 90, 90);\n"
"color: rgb(240, 240, 240);\n"
"border: 1px solid rgb(240, 240, 240);")
        self.LE_Consommation.setObjectName("LE_Consommation")
        self.gridLayout.addWidget(self.LE_Consommation, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setMinimumSize(QtCore.QSize(300, 15))
        self.label_5.setMaximumSize(QtCore.QSize(300, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setMinimumSize(QtCore.QSize(120, 15))
        self.label_6.setMaximumSize(QtCore.QSize(120, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setMinimumSize(QtCore.QSize(300, 30))
        self.label_4.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.LE_Total = QtWidgets.QLineEdit(Dialog)
        self.LE_Total.setMinimumSize(QtCore.QSize(120, 30))
        self.LE_Total.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.LE_Total.setFont(font)
        self.LE_Total.setStyleSheet("background-color: rgb(90, 90, 90);\n"
"color: rgb(240, 240, 240);\n"
"border: 1px solid rgb(240, 240, 240);")
        self.LE_Total.setReadOnly(True)
        self.LE_Total.setObjectName("LE_Total")
        self.gridLayout.addWidget(self.LE_Total, 4, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setMinimumSize(QtCore.QSize(300, 15))
        self.label_7.setMaximumSize(QtCore.QSize(300, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setMinimumSize(QtCore.QSize(120, 15))
        self.label_8.setMaximumSize(QtCore.QSize(120, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.B_Fermer = QtWidgets.QPushButton(Dialog)
        self.B_Fermer.setMinimumSize(QtCore.QSize(120, 60))
        self.B_Fermer.setMaximumSize(QtCore.QSize(60, 30))
        self.B_Fermer.setBaseSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.B_Fermer.setFont(font)
        self.B_Fermer.setAutoFillBackground(False)
        self.B_Fermer.setStyleSheet("background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0.5 rgba(70, 70, 70, 255), stop:1 rgba(200, 200, 200, 255));\n"
"color: rgb(240, 240, 240);")
        self.B_Fermer.setFlat(False)
        self.B_Fermer.setObjectName("B_Fermer")
        self.horizontalLayout_2.addWidget(self.B_Fermer, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.B_Inserer_total = QtWidgets.QPushButton(Dialog)
        self.B_Inserer_total.setMinimumSize(QtCore.QSize(120, 60))
        self.B_Inserer_total.setMaximumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.B_Inserer_total.setFont(font)
        self.B_Inserer_total.setAutoFillBackground(False)
        self.B_Inserer_total.setStyleSheet("background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0.5 rgba(70, 70, 70, 255), stop:1 rgba(200, 200, 200, 255));\n"
"color: rgb(240, 240, 240);")
        self.B_Inserer_total.setObjectName("B_Inserer_total")
        self.horizontalLayout_2.addWidget(self.B_Inserer_total, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.gridLayout.addLayout(self.horizontalLayout_2, 6, 0, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.LE_Distance, self.LE_Prix_carburant)
        Dialog.setTabOrder(self.LE_Prix_carburant, self.LE_Consommation)
        Dialog.setTabOrder(self.LE_Consommation, self.LE_Total)
        Dialog.setTabOrder(self.LE_Total, self.B_Inserer_total)
        Dialog.setTabOrder(self.B_Inserer_total, self.B_Fermer)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Calculatrice pour les trajets", None))
        self.label.setText(_translate("Dialog", "Indiquez la distance parcourue (en km)", None))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p>Indiquez le prix du carburant (en €/L)</p></body></html>", None))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p>Indiquez la consommation (en L/100 km)</p></body></html>", None))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>", None))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>", None))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p>TOTAL (en €)</p></body></html>", None))
        self.label_7.setText(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>", None))
        self.label_8.setText(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>", None))
        self.B_Fermer.setText(_translate("Dialog", "Fermer la\n"
"calculatrice", None))
        self.B_Inserer_total.setText(_translate("Dialog", "Insérer le total \n"
"dans une \n"
"nouvelle ligne", None))

