# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '10_Proto_10.ui'
#
# Created: Fri Jan 18 17:00:09 2019
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(975, 618)
        MainWindow.setMinimumSize(QtCore.QSize(975, 618))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.NoRole, brush)
        MainWindow.setPalette(palette)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.F_Boutons = QtGui.QFrame(self.centralwidget)
        self.F_Boutons.setMinimumSize(QtCore.QSize(110, 517))
        self.F_Boutons.setMaximumSize(QtCore.QSize(110, 16777215))
        self.F_Boutons.setFrameShape(QtGui.QFrame.Panel)
        self.F_Boutons.setFrameShadow(QtGui.QFrame.Raised)
        self.F_Boutons.setObjectName(_fromUtf8("F_Boutons"))
        self.verticalLayout = QtGui.QVBoxLayout(self.F_Boutons)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.B_Import_CSV = QtGui.QPushButton(self.F_Boutons)
        self.B_Import_CSV.setMinimumSize(QtCore.QSize(90, 90))
        self.B_Import_CSV.setMaximumSize(QtCore.QSize(90, 90))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.B_Import_CSV.setFont(font)
        self.B_Import_CSV.setAutoFillBackground(False)
        self.B_Import_CSV.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0.5 rgba(70, 70, 70, 255), stop:1 rgba(200, 200, 200, 255));\n"
"color: rgb(240, 240, 240);"))
        self.B_Import_CSV.setObjectName(_fromUtf8("B_Import_CSV"))
        self.verticalLayout.addWidget(self.B_Import_CSV)
        self.B_Traiter_lignes = QtGui.QPushButton(self.F_Boutons)
        self.B_Traiter_lignes.setMinimumSize(QtCore.QSize(90, 90))
        self.B_Traiter_lignes.setMaximumSize(QtCore.QSize(90, 90))
        self.B_Traiter_lignes.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0.5 rgba(70, 70, 70, 255), stop:1 rgba(200, 200, 200, 255));\n"
"color: rgb(240, 240, 240);"))
        self.B_Traiter_lignes.setObjectName(_fromUtf8("B_Traiter_lignes"))
        self.verticalLayout.addWidget(self.B_Traiter_lignes)
        self.B_Impression = QtGui.QPushButton(self.F_Boutons)
        self.B_Impression.setMinimumSize(QtCore.QSize(90, 90))
        self.B_Impression.setMaximumSize(QtCore.QSize(90, 90))
        self.B_Impression.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0.5 rgba(70, 70, 70, 255), stop:1 rgba(200, 200, 200, 255));\n"
"color: rgb(240, 240, 240);"))
        self.B_Impression.setObjectName(_fromUtf8("B_Impression"))
        self.verticalLayout.addWidget(self.B_Impression)
        self.B_Internet = QtGui.QPushButton(self.F_Boutons)
        self.B_Internet.setMinimumSize(QtCore.QSize(90, 90))
        self.B_Internet.setMaximumSize(QtCore.QSize(90, 90))
        self.B_Internet.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0.5 rgba(70, 70, 70, 255), stop:1 rgba(200, 200, 200, 255));\n"
"color: rgb(240, 240, 240);"))
        self.B_Internet.setObjectName(_fromUtf8("B_Internet"))
        self.verticalLayout.addWidget(self.B_Internet)
        spacerItem = QtGui.QSpacerItem(20, 110, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.B_Quitter = QtGui.QPushButton(self.F_Boutons)
        self.B_Quitter.setMinimumSize(QtCore.QSize(90, 90))
        self.B_Quitter.setMaximumSize(QtCore.QSize(90, 90))
        self.B_Quitter.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0.5 rgba(70, 70, 70, 255), stop:1 rgba(200, 200, 200, 255));\n"
"color: rgb(240, 240, 240);"))
        self.B_Quitter.setObjectName(_fromUtf8("B_Quitter"))
        self.verticalLayout.addWidget(self.B_Quitter)
        self.gridLayout_4.addWidget(self.F_Boutons, 0, 0, 2, 1)
        self.F_Infos_generales = QtGui.QFrame(self.centralwidget)
        self.F_Infos_generales.setMinimumSize(QtCore.QSize(840, 120))
        self.F_Infos_generales.setMaximumSize(QtCore.QSize(16777215, 120))
        self.F_Infos_generales.setStyleSheet(_fromUtf8("color: rgb(240, 240, 240);"))
        self.F_Infos_generales.setFrameShape(QtGui.QFrame.Panel)
        self.F_Infos_generales.setFrameShadow(QtGui.QFrame.Raised)
        self.F_Infos_generales.setLineWidth(1)
        self.F_Infos_generales.setObjectName(_fromUtf8("F_Infos_generales"))
        self.gridLayout = QtGui.QGridLayout(self.F_Infos_generales)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_18 = QtGui.QLabel(self.F_Infos_generales)
        self.label_18.setMinimumSize(QtCore.QSize(34, 16))
        self.label_18.setMaximumSize(QtCore.QSize(34, 16))
        self.label_18.setText(_fromUtf8(""))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout.addWidget(self.label_18, 3, 3, 1, 1)
        self.label = QtGui.QLabel(self.F_Infos_generales)
        self.label.setMinimumSize(QtCore.QSize(110, 20))
        self.label.setMaximumSize(QtCore.QSize(110, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.L_Nom_du_fichier_de_balance_charge = QtGui.QLabel(self.F_Infos_generales)
        self.L_Nom_du_fichier_de_balance_charge.setObjectName(_fromUtf8("L_Nom_du_fichier_de_balance_charge"))
        self.gridLayout.addWidget(self.L_Nom_du_fichier_de_balance_charge, 3, 9, 1, 1)
        self.label_3 = QtGui.QLabel(self.F_Infos_generales)
        self.label_3.setMinimumSize(QtCore.QSize(170, 20))
        self.label_3.setMaximumSize(QtCore.QSize(170, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 8, 1, 1)
        self.L_Date_update = QtGui.QLabel(self.F_Infos_generales)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.L_Date_update.setPalette(palette)
        self.L_Date_update.setObjectName(_fromUtf8("L_Date_update"))
        self.gridLayout.addWidget(self.L_Date_update, 0, 9, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(422, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 7, 1, 1)
        self.label_4 = QtGui.QLabel(self.F_Infos_generales)
        self.label_4.setMinimumSize(QtCore.QSize(110, 20))
        self.label_4.setMaximumSize(QtCore.QSize(110, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.F_Infos_generales)
        self.label_2.setMinimumSize(QtCore.QSize(110, 20))
        self.label_2.setMaximumSize(QtCore.QSize(110, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 7, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 7, 1, 1)
        self.L_Nom_du_fichier_de_comptes_charge = QtGui.QLabel(self.F_Infos_generales)
        self.L_Nom_du_fichier_de_comptes_charge.setObjectName(_fromUtf8("L_Nom_du_fichier_de_comptes_charge"))
        self.gridLayout.addWidget(self.L_Nom_du_fichier_de_comptes_charge, 2, 9, 1, 1)
        self.label_7 = QtGui.QLabel(self.F_Infos_generales)
        self.label_7.setMinimumSize(QtCore.QSize(170, 20))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 3, 8, 1, 1)
        self.label_5 = QtGui.QLabel(self.F_Infos_generales)
        self.label_5.setMinimumSize(QtCore.QSize(170, 20))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 2, 8, 1, 1)
        self.L_total_comptes_lui = QtGui.QLabel(self.F_Infos_generales)
        self.L_total_comptes_lui.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.L_total_comptes_lui.setObjectName(_fromUtf8("L_total_comptes_lui"))
        self.gridLayout.addWidget(self.L_total_comptes_lui, 2, 4, 1, 1)
        self.L_total_balance_lui = QtGui.QLabel(self.F_Infos_generales)
        self.L_total_balance_lui.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.L_total_balance_lui.setObjectName(_fromUtf8("L_total_balance_lui"))
        self.gridLayout.addWidget(self.L_total_balance_lui, 2, 5, 1, 1)
        self.L_total_balance_elle = QtGui.QLabel(self.F_Infos_generales)
        self.L_total_balance_elle.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.L_total_balance_elle.setObjectName(_fromUtf8("L_total_balance_elle"))
        self.gridLayout.addWidget(self.L_total_balance_elle, 3, 5, 1, 1)
        self.L_total_comptes_elle = QtGui.QLabel(self.F_Infos_generales)
        self.L_total_comptes_elle.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.L_total_comptes_elle.setObjectName(_fromUtf8("L_total_comptes_elle"))
        self.gridLayout.addWidget(self.L_total_comptes_elle, 3, 4, 1, 1)
        self.label_24 = QtGui.QLabel(self.F_Infos_generales)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout.addWidget(self.label_24, 1, 4, 1, 1)
        self.label_25 = QtGui.QLabel(self.F_Infos_generales)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout.addWidget(self.label_25, 1, 5, 1, 1)
        self.label_16 = QtGui.QLabel(self.F_Infos_generales)
        self.label_16.setMinimumSize(QtCore.QSize(34, 16))
        self.label_16.setMaximumSize(QtCore.QSize(34, 16))
        self.label_16.setText(_fromUtf8(""))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.label_16, 1, 3, 1, 1)
        self.label_17 = QtGui.QLabel(self.F_Infos_generales)
        self.label_17.setMinimumSize(QtCore.QSize(34, 16))
        self.label_17.setMaximumSize(QtCore.QSize(34, 16))
        self.label_17.setText(_fromUtf8(""))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout.addWidget(self.label_17, 2, 3, 1, 1)
        self.L_Total_lui = QtGui.QLabel(self.F_Infos_generales)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.L_Total_lui.setFont(font)
        self.L_Total_lui.setObjectName(_fromUtf8("L_Total_lui"))
        self.gridLayout.addWidget(self.L_Total_lui, 2, 2, 1, 1)
        self.L_Total_elle = QtGui.QLabel(self.F_Infos_generales)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.L_Total_elle.setFont(font)
        self.L_Total_elle.setObjectName(_fromUtf8("L_Total_elle"))
        self.gridLayout.addWidget(self.L_Total_elle, 3, 2, 1, 1)
        self.L_Total = QtGui.QLabel(self.F_Infos_generales)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.L_Total.setFont(font)
        self.L_Total.setObjectName(_fromUtf8("L_Total"))
        self.gridLayout.addWidget(self.L_Total, 0, 2, 1, 1)
        self.label_26 = QtGui.QLabel(self.F_Infos_generales)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout.addWidget(self.label_26, 1, 6, 1, 1)
        self.L_total_annee_precedente_lui = QtGui.QLabel(self.F_Infos_generales)
        self.L_total_annee_precedente_lui.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.L_total_annee_precedente_lui.setObjectName(_fromUtf8("L_total_annee_precedente_lui"))
        self.gridLayout.addWidget(self.L_total_annee_precedente_lui, 2, 6, 1, 1)
        self.L_total_annee_precedente_elle = QtGui.QLabel(self.F_Infos_generales)
        self.L_total_annee_precedente_elle.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.L_total_annee_precedente_elle.setObjectName(_fromUtf8("L_total_annee_precedente_elle"))
        self.gridLayout.addWidget(self.L_total_annee_precedente_elle, 3, 6, 1, 1)
        self.gridLayout_4.addWidget(self.F_Infos_generales, 0, 1, 1, 1)
        self.TW_Donnees = QtGui.QTabWidget(self.centralwidget)
        self.TW_Donnees.setMinimumSize(QtCore.QSize(817, 420))
        self.TW_Donnees.setStyleSheet(_fromUtf8("background-color: rgb(90, 90, 90);"))
        self.TW_Donnees.setObjectName(_fromUtf8("TW_Donnees"))
        self.T_Comptes = QtGui.QWidget()
        self.T_Comptes.setMinimumSize(QtCore.QSize(831, 395))
        self.T_Comptes.setStyleSheet(_fromUtf8(""))
        self.T_Comptes.setObjectName(_fromUtf8("T_Comptes"))
        self.gridLayout_3 = QtGui.QGridLayout(self.T_Comptes)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.TV_Comptes = QtGui.QTableView(self.T_Comptes)
        self.TV_Comptes.setMinimumSize(QtCore.QSize(817, 382))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.TV_Comptes.setPalette(palette)
        self.TV_Comptes.setObjectName(_fromUtf8("TV_Comptes"))
        self.gridLayout_3.addWidget(self.TV_Comptes, 0, 0, 1, 1)
        self.TW_Donnees.addTab(self.T_Comptes, _fromUtf8(""))
        self.T_Balance = QtGui.QWidget()
        self.T_Balance.setMinimumSize(QtCore.QSize(831, 395))
        self.T_Balance.setObjectName(_fromUtf8("T_Balance"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.T_Balance)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.F_Balance = QtGui.QFrame(self.T_Balance)
        self.F_Balance.setMinimumSize(QtCore.QSize(817, 170))
        self.F_Balance.setMaximumSize(QtCore.QSize(16777215, 170))
        self.F_Balance.setFrameShape(QtGui.QFrame.Panel)
        self.F_Balance.setFrameShadow(QtGui.QFrame.Raised)
        self.F_Balance.setObjectName(_fromUtf8("F_Balance"))
        self.gridLayout_2 = QtGui.QGridLayout(self.F_Balance)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.CB_payeur = QtGui.QComboBox(self.F_Balance)
        self.CB_payeur.setMinimumSize(QtCore.QSize(150, 30))
        self.CB_payeur.setMaximumSize(QtCore.QSize(150, 30))
        self.CB_payeur.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0.5 rgba(70, 70, 70, 255), stop:1 rgba(200, 200, 200, 255));\n"
"color: rgb(240, 240, 240);"))
        self.CB_payeur.setObjectName(_fromUtf8("CB_payeur"))
        self.CB_payeur.addItem(_fromUtf8(""))
        self.CB_payeur.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.CB_payeur, 2, 3, 1, 1)
        self.label_9 = QtGui.QLabel(self.F_Balance)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 2, 2, 1, 1)
        self.label_12 = QtGui.QLabel(self.F_Balance)
        self.label_12.setMinimumSize(QtCore.QSize(34, 16))
        self.label_12.setMaximumSize(QtCore.QSize(34, 16))
        self.label_12.setText(_fromUtf8(""))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 2, 1, 1, 1)
        self.CW_Choix_de_la_date = QtGui.QCalendarWidget(self.F_Balance)
        self.CW_Choix_de_la_date.setMinimumSize(QtCore.QSize(256, 141))
        self.CW_Choix_de_la_date.setMaximumSize(QtCore.QSize(256, 141))
        self.CW_Choix_de_la_date.setObjectName(_fromUtf8("CW_Choix_de_la_date"))
        self.gridLayout_2.addWidget(self.CW_Choix_de_la_date, 0, 0, 3, 1)
        self.B_Ajouter_dans_balance = QtGui.QPushButton(self.F_Balance)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.B_Ajouter_dans_balance.sizePolicy().hasHeightForWidth())
        self.B_Ajouter_dans_balance.setSizePolicy(sizePolicy)
        self.B_Ajouter_dans_balance.setMinimumSize(QtCore.QSize(100, 150))
        self.B_Ajouter_dans_balance.setMaximumSize(QtCore.QSize(100, 150))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(1.0, 1.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.RepeatSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.5, QtGui.QColor(70, 70, 70))
        gradient.setColorAt(1.0, QtGui.QColor(200, 200, 200))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(1.0, 1.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.RepeatSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.5, QtGui.QColor(70, 70, 70))
        gradient.setColorAt(1.0, QtGui.QColor(200, 200, 200))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(1.0, 1.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.RepeatSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.5, QtGui.QColor(70, 70, 70))
        gradient.setColorAt(1.0, QtGui.QColor(200, 200, 200))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(1.0, 1.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.RepeatSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.5, QtGui.QColor(70, 70, 70))
        gradient.setColorAt(1.0, QtGui.QColor(200, 200, 200))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(1.0, 1.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.RepeatSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.5, QtGui.QColor(70, 70, 70))
        gradient.setColorAt(1.0, QtGui.QColor(200, 200, 200))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(1.0, 1.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.RepeatSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.5, QtGui.QColor(70, 70, 70))
        gradient.setColorAt(1.0, QtGui.QColor(200, 200, 200))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(1.0, 1.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.RepeatSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.5, QtGui.QColor(70, 70, 70))
        gradient.setColorAt(1.0, QtGui.QColor(200, 200, 200))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(1.0, 1.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.RepeatSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.5, QtGui.QColor(70, 70, 70))
        gradient.setColorAt(1.0, QtGui.QColor(200, 200, 200))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(1.0, 1.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.RepeatSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.5, QtGui.QColor(70, 70, 70))
        gradient.setColorAt(1.0, QtGui.QColor(200, 200, 200))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.B_Ajouter_dans_balance.setPalette(palette)
        self.B_Ajouter_dans_balance.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0.5 rgba(70, 70, 70, 255), stop:1 rgba(200, 200, 200, 255));\n"
"color: rgb(240, 240, 240);"))
        self.B_Ajouter_dans_balance.setObjectName(_fromUtf8("B_Ajouter_dans_balance"))
        self.gridLayout_2.addWidget(self.B_Ajouter_dans_balance, 0, 6, 3, 1)
        self.label_6 = QtGui.QLabel(self.F_Balance)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 0, 2, 1, 1)
        self.LE_Libelle = QtGui.QLineEdit(self.F_Balance)
        self.LE_Libelle.setMinimumSize(QtCore.QSize(150, 30))
        self.LE_Libelle.setMaximumSize(QtCore.QSize(150, 30))
        self.LE_Libelle.setStyleSheet(_fromUtf8("background-color: rgb(90, 90, 90);\n"
"color: rgb(240, 240, 240);\n"
"border: 1px solid rgb(240, 240, 240);"))
        self.LE_Libelle.setObjectName(_fromUtf8("LE_Libelle"))
        self.gridLayout_2.addWidget(self.LE_Libelle, 0, 3, 1, 1)
        self.label_10 = QtGui.QLabel(self.F_Balance)
        self.label_10.setMinimumSize(QtCore.QSize(34, 16))
        self.label_10.setMaximumSize(QtCore.QSize(34, 16))
        self.label_10.setText(_fromUtf8(""))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 0, 1, 1, 1)
        self.LE_Montant = QtGui.QLineEdit(self.F_Balance)
        self.LE_Montant.setMinimumSize(QtCore.QSize(150, 30))
        self.LE_Montant.setMaximumSize(QtCore.QSize(150, 30))
        self.LE_Montant.setStyleSheet(_fromUtf8("background-color: rgb(90, 90, 90);\n"
"color: rgb(240, 240, 240);\n"
"border: 1px solid rgb(240, 240, 240);\n"
""))
        self.LE_Montant.setObjectName(_fromUtf8("LE_Montant"))
        self.gridLayout_2.addWidget(self.LE_Montant, 1, 3, 1, 1)
        self.label_11 = QtGui.QLabel(self.F_Balance)
        self.label_11.setMinimumSize(QtCore.QSize(34, 16))
        self.label_11.setMaximumSize(QtCore.QSize(34, 16))
        self.label_11.setText(_fromUtf8(""))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.F_Balance)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 1, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.F_Balance)
        self.label_13.setMinimumSize(QtCore.QSize(34, 16))
        self.label_13.setMaximumSize(QtCore.QSize(34, 16))
        self.label_13.setText(_fromUtf8(""))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 0, 5, 1, 1)
        self.label_14 = QtGui.QLabel(self.F_Balance)
        self.label_14.setMinimumSize(QtCore.QSize(34, 16))
        self.label_14.setMaximumSize(QtCore.QSize(34, 16))
        self.label_14.setText(_fromUtf8(""))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 1, 5, 1, 1)
        self.label_15 = QtGui.QLabel(self.F_Balance)
        self.label_15.setMinimumSize(QtCore.QSize(34, 16))
        self.label_15.setMaximumSize(QtCore.QSize(34, 16))
        self.label_15.setText(_fromUtf8(""))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 2, 5, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 0, 4, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 1, 4, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 2, 4, 1, 1)
        self.verticalLayout_2.addWidget(self.F_Balance)
        self.TV_Balance = QtGui.QTableView(self.T_Balance)
        self.TV_Balance.setMinimumSize(QtCore.QSize(817, 206))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.TV_Balance.setPalette(palette)
        self.TV_Balance.setObjectName(_fromUtf8("TV_Balance"))
        self.verticalLayout_2.addWidget(self.TV_Balance)
        self.TW_Donnees.addTab(self.T_Balance, _fromUtf8(""))
        self.gridLayout_4.addWidget(self.TW_Donnees, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.TW_Donnees.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Comptes", None))
        self.B_Import_CSV.setText(_translate("MainWindow", "1 - Importer\n"
"un fichier CSV", None))
        self.B_Traiter_lignes.setText(_translate("MainWindow", "2 - Traiter \n"
"des lignes", None))
        self.B_Impression.setText(_translate("MainWindow", "3 - Imprimer\n"
"les comptes \n"
"sur une période", None))
        self.B_Internet.setText(_translate("MainWindow", "4 - Aller sur\n"
"le site de \n"
"la banque", None))
        self.B_Quitter.setText(_translate("MainWindow", "Quitter", None))
        self.label.setText(_translate("MainWindow", "TOTAL sur le compte", None))
        self.L_Nom_du_fichier_de_balance_charge.setText(_translate("MainWindow", "TextLabel", None))
        self.label_3.setText(_translate("MainWindow", "Date de la dernière mise-à-jour", None))
        self.L_Date_update.setText(_translate("MainWindow", "TextLabel", None))
        self.label_4.setText(_translate("MainWindow", "Total elle", None))
        self.label_2.setText(_translate("MainWindow", "Total lui", None))
        self.L_Nom_du_fichier_de_comptes_charge.setText(_translate("MainWindow", "TextLabel", None))
        self.label_7.setText(_translate("MainWindow", "Fichier de balance chargé", None))
        self.label_5.setText(_translate("MainWindow", "Fichier de comptes chargé", None))
        self.L_total_comptes_lui.setText(_translate("MainWindow", "0.0", None))
        self.L_total_balance_lui.setText(_translate("MainWindow", "0.0", None))
        self.L_total_balance_elle.setText(_translate("MainWindow", "0.0", None))
        self.L_total_comptes_elle.setText(_translate("MainWindow", "0.0", None))
        self.label_24.setText(_translate("MainWindow", "Totaux comptes", None))
        self.label_25.setText(_translate("MainWindow", "Totaux balance", None))
        self.L_Total_lui.setText(_translate("MainWindow", "0.0", None))
        self.L_Total_elle.setText(_translate("MainWindow", "0.0", None))
        self.L_Total.setText(_translate("MainWindow", "0.0", None))
        self.label_26.setText(_translate("MainWindow", "<html><head/><body><p>Totaux année précédente</p></body></html>", None))
        self.L_total_annee_precedente_lui.setText(_translate("MainWindow", "0.0", None))
        self.L_total_annee_precedente_elle.setText(_translate("MainWindow", "0.0", None))
        self.TW_Donnees.setTabText(self.TW_Donnees.indexOf(self.T_Comptes), _translate("MainWindow", "Comptes", None))
        self.CB_payeur.setItemText(0, _translate("MainWindow", "lui", None))
        self.CB_payeur.setItemText(1, _translate("MainWindow", "elle", None))
        self.label_9.setText(_translate("MainWindow", "Payé par", None))
        self.B_Ajouter_dans_balance.setText(_translate("MainWindow", "Ajouter", None))
        self.label_6.setText(_translate("MainWindow", "Libellé", None))
        self.label_8.setText(_translate("MainWindow", "Montant (€)", None))
        self.TW_Donnees.setTabText(self.TW_Donnees.indexOf(self.T_Balance), _translate("MainWindow", "Balance", None))

