# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '02_Calculatrice_trajets_2.ui'
#
# Created: Fri Jan 18 16:37:56 2019
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(450, 295)
        Dialog.setMinimumSize(QtCore.QSize(450, 295))
        Dialog.setMaximumSize(QtCore.QSize(450, 295))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Dialog.setPalette(palette)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setMinimumSize(QtCore.QSize(300, 30))
        self.label.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.LE_Distance = QtGui.QLineEdit(Dialog)
        self.LE_Distance.setMinimumSize(QtCore.QSize(120, 30))
        self.LE_Distance.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LE_Distance.setFont(font)
        self.LE_Distance.setStyleSheet(_fromUtf8("background-color: rgb(90, 90, 90);\n"
"color: rgb(240, 240, 240);\n"
"border: 1px solid rgb(240, 240, 240);"))
        self.LE_Distance.setObjectName(_fromUtf8("LE_Distance"))
        self.gridLayout.addWidget(self.LE_Distance, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setMinimumSize(QtCore.QSize(300, 30))
        self.label_2.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.LE_Prix_carburant = QtGui.QLineEdit(Dialog)
        self.LE_Prix_carburant.setMinimumSize(QtCore.QSize(120, 30))
        self.LE_Prix_carburant.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LE_Prix_carburant.setFont(font)
        self.LE_Prix_carburant.setStyleSheet(_fromUtf8("background-color: rgb(90, 90, 90);\n"
"color: rgb(240, 240, 240);\n"
"border: 1px solid rgb(240, 240, 240);"))
        self.LE_Prix_carburant.setObjectName(_fromUtf8("LE_Prix_carburant"))
        self.gridLayout.addWidget(self.LE_Prix_carburant, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setMinimumSize(QtCore.QSize(300, 30))
        self.label_3.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.LE_Consommation = QtGui.QLineEdit(Dialog)
        self.LE_Consommation.setMinimumSize(QtCore.QSize(120, 30))
        self.LE_Consommation.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LE_Consommation.setFont(font)
        self.LE_Consommation.setStyleSheet(_fromUtf8("background-color: rgb(90, 90, 90);\n"
"color: rgb(240, 240, 240);\n"
"border: 1px solid rgb(240, 240, 240);"))
        self.LE_Consommation.setObjectName(_fromUtf8("LE_Consommation"))
        self.gridLayout.addWidget(self.LE_Consommation, 2, 1, 1, 1)
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setMinimumSize(QtCore.QSize(300, 15))
        self.label_5.setMaximumSize(QtCore.QSize(300, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setMinimumSize(QtCore.QSize(120, 15))
        self.label_6.setMaximumSize(QtCore.QSize(120, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 3, 1, 1, 1)
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setMinimumSize(QtCore.QSize(300, 30))
        self.label_4.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.LE_Total = QtGui.QLineEdit(Dialog)
        self.LE_Total.setMinimumSize(QtCore.QSize(120, 30))
        self.LE_Total.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.LE_Total.setFont(font)
        self.LE_Total.setStyleSheet(_fromUtf8("background-color: rgb(90, 90, 90);\n"
"color: rgb(240, 240, 240);\n"
"border: 1px solid rgb(240, 240, 240);"))
        self.LE_Total.setReadOnly(True)
        self.LE_Total.setObjectName(_fromUtf8("LE_Total"))
        self.gridLayout.addWidget(self.LE_Total, 4, 1, 1, 1)
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setMinimumSize(QtCore.QSize(300, 15))
        self.label_7.setMaximumSize(QtCore.QSize(300, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setMinimumSize(QtCore.QSize(120, 15))
        self.label_8.setMaximumSize(QtCore.QSize(120, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 5, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.B_Fermer = QtGui.QPushButton(Dialog)
        self.B_Fermer.setMinimumSize(QtCore.QSize(120, 60))
        self.B_Fermer.setMaximumSize(QtCore.QSize(60, 30))
        self.B_Fermer.setBaseSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.B_Fermer.setFont(font)
        self.B_Fermer.setAutoFillBackground(False)
        self.B_Fermer.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0.5 rgba(70, 70, 70, 255), stop:1 rgba(200, 200, 200, 255));\n"
"color: rgb(240, 240, 240);"))
        self.B_Fermer.setFlat(False)
        self.B_Fermer.setObjectName(_fromUtf8("B_Fermer"))
        self.horizontalLayout_2.addWidget(self.B_Fermer, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.B_Inserer_total = QtGui.QPushButton(Dialog)
        self.B_Inserer_total.setMinimumSize(QtCore.QSize(120, 60))
        self.B_Inserer_total.setMaximumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.B_Inserer_total.setFont(font)
        self.B_Inserer_total.setAutoFillBackground(False)
        self.B_Inserer_total.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0.5 rgba(70, 70, 70, 255), stop:1 rgba(200, 200, 200, 255));\n"
"color: rgb(240, 240, 240);"))
        self.B_Inserer_total.setObjectName(_fromUtf8("B_Inserer_total"))
        self.horizontalLayout_2.addWidget(self.B_Inserer_total, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.gridLayout.addLayout(self.horizontalLayout_2, 6, 0, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.LE_Distance, self.LE_Prix_carburant)
        Dialog.setTabOrder(self.LE_Prix_carburant, self.LE_Consommation)
        Dialog.setTabOrder(self.LE_Consommation, self.LE_Total)
        Dialog.setTabOrder(self.LE_Total, self.B_Inserer_total)
        Dialog.setTabOrder(self.B_Inserer_total, self.B_Fermer)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Calculatrice pour les trajets", None))
        self.label.setText(_translate("Dialog", "Indiquez la distance parcourue (en km)", None))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p>Indiquez le prix du carburant (en €/L)</p></body></html>", None))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p>Indiquez la consommation (en L/100 km)</p></body></html>", None))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>", None))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>", None))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p>TOTAL (en €)</p></body></html>", None))
        self.label_7.setText(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>", None))
        self.label_8.setText(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>", None))
        self.B_Fermer.setText(_translate("Dialog", "Fermer la\n"
"calculatrice", None))
        self.B_Inserer_total.setText(_translate("Dialog", "Insérer le total \n"
"dans une \n"
"nouvelle ligne", None))

